# Capstone Project: Full Report: Car Accident Severity

Road Accident is the most undesirable and unexpected thing to occur to a road user, though they happen quite often. Unfortunately, we can see a minatory rise of road accidents, conspicuously highroad accidents over the past few years. It has a massive impact on society as well as in the economy of the country as there is an immense cost of fatalities and injuries. According to a recent report, annually on an average 9,000 lives have been taken by road accidents and lead to almost 28,000 injuries. This record indicates the idea to leverage the accident data that you found to predict the different accidents' severity and come up with solution which can be benefial to the governement. Besides this, according to WHO, the economic cost of road accidents to a developing country like us is 2-3% of GDP, which is a significant loss for a country like ours. Moreover, reducing this loss has become a great matter of concern for our country now.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler,PolynomialFeatures
from sklearn.linear_model import LinearRegression
%matplotlib inline

In [43]:
print("Hello Capstone Project Course!")

Hello Capstone Project Course!


In [32]:
excel_file_path = "D:\Data Science\Capstone Projects\IBM\Data-Collisions.csv"

In [33]:
df = pd.read_csv(excel_file_path)

In [34]:
dtype={'user_id': int}

In [35]:
print(df.columns)

Index(['SEVERITYCODE', 'X', 'Y', 'OBJECTID', 'INCKEY', 'COLDETKEY', 'REPORTNO',
       'STATUS', 'ADDRTYPE', 'INTKEY', 'LOCATION', 'EXCEPTRSNCODE',
       'EXCEPTRSNDESC', 'SEVERITYCODE.1', 'SEVERITYDESC', 'COLLISIONTYPE',
       'PERSONCOUNT', 'PEDCOUNT', 'PEDCYLCOUNT', 'VEHCOUNT', 'INCDATE',
       'INCDTTM', 'JUNCTIONTYPE', 'SDOT_COLCODE', 'SDOT_COLDESC',
       'INATTENTIONIND', 'UNDERINFL', 'WEATHER', 'ROADCOND', 'LIGHTCOND',
       'PEDROWNOTGRNT', 'SDOTCOLNUM', 'SPEEDING', 'ST_COLCODE', 'ST_COLDESC',
       'SEGLANEKEY', 'CROSSWALKKEY', 'HITPARKEDCAR'],
      dtype='object')


In [13]:
df_info = df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194673 entries, 0 to 194672
Data columns (total 38 columns):
SEVERITYCODE      194673 non-null int64
X                 189339 non-null float64
Y                 189339 non-null float64
OBJECTID          194673 non-null int64
INCKEY            194673 non-null int64
COLDETKEY         194673 non-null int64
REPORTNO          194673 non-null object
STATUS            194673 non-null object
ADDRTYPE          192747 non-null object
INTKEY            65070 non-null float64
LOCATION          191996 non-null object
EXCEPTRSNCODE     84811 non-null object
EXCEPTRSNDESC     5638 non-null object
SEVERITYCODE.1    194673 non-null int64
SEVERITYDESC      194673 non-null object
COLLISIONTYPE     189769 non-null object
PERSONCOUNT       194673 non-null int64
PEDCOUNT          194673 non-null int64
PEDCYLCOUNT       194673 non-null int64
VEHCOUNT          194673 non-null int64
INCDATE           194673 non-null object
INCDTTM           194673 non-null obje

In [36]:
print(df_info)

None


In [25]:
print(df.describe())

        SEVERITYCODE              X              Y       OBJECTID  \
count  194673.000000  189339.000000  189339.000000  194673.000000   
mean        1.298901    -122.330518      47.619543  108479.364930   
std         0.457778       0.029976       0.056157   62649.722558   
min         1.000000    -122.419091      47.495573       1.000000   
25%         1.000000    -122.348673      47.575956   54267.000000   
50%         1.000000    -122.330224      47.615369  106912.000000   
75%         2.000000    -122.311937      47.663664  162272.000000   
max         2.000000    -122.238949      47.734142  219547.000000   

              INCKEY      COLDETKEY         INTKEY  SEVERITYCODE.1  \
count  194673.000000  194673.000000   65070.000000   194673.000000   
mean   141091.456350  141298.811381   37558.450576        1.298901   
std     86634.402737   86986.542110   51745.990273        0.457778   
min      1001.000000    1001.000000   23807.000000        1.000000   
25%     70383.000000   70383

In [37]:
print(df.describe()['OBJECTID'])

count    194673.000000
mean     108479.364930
std       62649.722558
min           1.000000
25%       54267.000000
50%      106912.000000
75%      162272.000000
max      219547.000000
Name: OBJECTID, dtype: float64


In [40]:
groupby_df =df.groupby(['OBJECTID']).max()

KeyboardInterrupt: 

In [21]:
np.arange(10,2,-1)

array([10,  9,  8,  7,  6,  5,  4,  3])

In [25]:
np.linspace(1,8,8)

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [26]:
np.logspace(1,8,8)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08])

In [31]:
np.random.rand(2,2,3)

array([[[0.79726404, 0.33578147, 0.42910877],
        [0.41211893, 0.64058657, 0.65041528]],

       [[0.17331284, 0.00389461, 0.08365768],
        [0.38966277, 0.13144242, 0.59534763]]])

In [30]:
np.random.rand(2,2,2)

array([[[0.31389581, 0.76075521],
        [0.95565006, 0.45429968]],

       [[0.18238537, 0.00676772],
        [0.67455169, 0.1488526 ]]])

In [38]:
d = np.random.randint(0,10,size=(5,5))

In [40]:
d[:,:]

array([[3, 1, 8, 5, 2],
       [8, 7, 3, 1, 9],
       [6, 0, 1, 7, 7],
       [1, 1, 2, 3, 9],
       [6, 0, 3, 8, 1]])

In [49]:
d[2:,1]

array([0, 1, 0])

In [50]:
d[2,2]

1

In [69]:
a=np.zeros((3,3))

In [70]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
b=np.zeros((3,3))

In [64]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [58]:
d

array([[3, 1, 8, 5, 2],
       [8, 7, 3, 1, 9],
       [6, 0, 1, 7, 7],
       [1, 1, 2, 3, 9],
       [6, 0, 3, 8, 1]])

In [73]:
np.concatenate([a,b], axis=1)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [78]:
np.hstack([a,b]) #inoder to place horzontally

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [79]:
np.vstack([a,b])  #inoder to place vertically

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [80]:
d1,d2=np.vsplit(d,[2])

In [81]:
d1

array([[3, 1, 8, 5, 2],
       [8, 7, 3, 1, 9]])

In [82]:
d2

array([[6, 0, 1, 7, 7],
       [1, 1, 2, 3, 9],
       [6, 0, 3, 8, 1]])

In [83]:
d.ndim #number of dimension

2

In [84]:
d.shape #type of shappe above one is 5 row 5 column

(5, 5)

In [85]:
d.size #number of elements

25

In [87]:
a=np.array([1,2,3,4,5,6])

In [88]:
a

array([1, 2, 3, 4, 5, 6])

In [89]:
a.shape

(6,)

In [97]:
a.reshape(2,-2)

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
z =np.array([4,8])

In [112]:
z

array([4, 8])

In [113]:
z.shape

(2,)

In [114]:
sum(a)

21

In [115]:
np.sum(a)

21

In [116]:
np.max(a)

6

In [118]:
a.max()

6

In [ ]:
a

In [125]:
a = np.random.randint(1,100,size=(6,6))

In [126]:
np.sum(a,axis=1)

array([297, 253, 428, 244, 329, 357])

In [127]:
a

array([[87, 63, 47, 56, 20, 24],
       [31, 21, 78, 38, 37, 48],
       [58, 91, 56, 97, 56, 70],
       [ 9, 57, 99,  5, 25, 49],
       [73, 62, 82, 92,  9, 11],
       [30, 59, 54, 85, 52, 77]])

In [128]:
a=np.array([1,2,3,4,5])

In [129]:
b=np.array([6,7,8,10,15])

In [132]:
a+b

array([ 7,  9, 11, 14, 20])

In [145]:
a+6

array([[7, 8, 9]])

In [138]:
a=np.array([[1,2,3]])

In [143]:
b=np.array([[1,2,3],[1,4,3],[1,4,3]])

In [144]:
a+b

array([[2, 4, 6],
       [2, 6, 6],
       [2, 6, 6]])

#Assignments

In [6]:
store = np.array(["X", "Z", "Z", "Z"])
cost = np.array([7, 1, 9, 4])
select_cost = cost[store == "X"]
print(select_cost)

[7]
